server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ZarbaliyevOzal/spring-boot-ecom-starter-config.git
          default-label: main